before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-setuptools python3-dev python-virtualenv python-pip
language: python
python:
  - "3.4"
install:
  - "pip install hitch"
  - "cd tests"
  - "hitch init"
script:
  - "hitch test . --settings ci.settings"
